baseURL = 'https://alexpham15010305.github.io/' # Update this with your actual domain
languageCode = 'en-us'
title = 'Phạm Tùng Lâm - DevOps Engineer & Solution Architect'
theme = 'LoveIt'

# Copyright description used only for seo schema
copyright = "© 2025 Phạm Tùng Lâm. All rights reserved."

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    title = "Technical Articles & Insights"
  [[menu.main]]
    weight = 2
    identifier = "about"
    name = "About"
    url = "/posts/about_me/"
    title = "About Phạm Tùng Lâm"
  [[menu.main]]
    weight = 3
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    title = "Browse by Technology"
  [[menu.main]]
    weight = 4
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    title = "Browse by Category"

[params]
  # Site info
  version = "0.2.X"
  description = "DevOps Engineer & Solution Architect specializing in AWS, Kubernetes, CI/CD, and Infrastructure as Code"
  keywords = ["DevOps", "AWS", "Kubernetes", "Docker", "CI/CD", "Infrastructure as Code", "Terraform", "Ansible"]
  
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  
  # public git repo url
  gitRepo = "https://github.com/PhaTLa/myBlogSite" # Update with your actual repo
  
  # date format
  dateFormat = "2006-01-02"
  
  # website images for Open Graph and Twitter Cards
  images = ["https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/avatar_400x400.png"] # Add your professional photo here
  
  # Author config
  [params.author]
    name = "Phạm Tùng Lâm"
    email = "phamtunglam.workmail.public@gmail.com"
    link = "https://www.linkedin.com/in/alexpham15010305"
    avatar = "https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/avatar_400x400.png" # Add your professional photo

  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Alex Pham's Blog"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .ico
    svgFavicon = "/favicon.svg"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  # Search config
  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "Search technical content..."
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 50
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  # Home page config
  [params.home]
    # RSS count
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/avatar_400x400.png"
      # title shown in home page (HTML format is supported)
      title = "Phạm Tùng Lâm"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "DevOps Engineer"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "Passionate about building and optimizing the bridges between development and operations"
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6

  # Social config in home page
  [params.social]
    GitHub = "PhaTLa"
    Linkedin = "alexpham15010305"
    Email = "phamtunglam.workmail.public@gmail.com"
    RSS = true

  # Page global config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show the full text content in RSS
    rssFullText = false
    # Page style ["normal", "wide"]
    pageStyle = "normal"
    # whether to enable series navigation
    seriesNavigation = true
    # enable the author avatar
    authorAvatar = true
    # Auto Bookmark Support
    autoBookmark = false
    # whether to enable wordCount
    wordCount = true
    # whether to enable readingTime
    readingTime = true
    # end of post flag
    endFlag = ""
    # whether to enable instant page loading
    instantPage = false

    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
      # position of TOC ["left", "right"]
      position = "right"
    
    # Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # whether to show the edit button of the code block
      edit = false
      # the maximum number of lines of displayed code by default
      maxShownLines = 50
    
    # KaTeX mathematical formulas
    [params.page.math]
      enable = false
      # default inline delimiter is $ ... $ and \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # default block delimiter is $$ ... $$ and \[ ... \]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    
    # Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v10"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v10"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    
    # social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      HackerNews = false
      Reddit = false
      VK = false
      Pinterest = false
      Tumblr = false
      WhatsApp = false
      Telegram = false
      Weibo = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    
    # Comment config
    [params.page.comment]
      enable = false

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/AlexPhamBlog_logo.png"
      # title name
      name = "Alex Pham's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # Site creation time
    since = 2025
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # Site SEO config
  [params.seo]
    # image URL
    image = "https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/AlexPhamBlog_logo.png"
    # thumbnail URL
    thumbnailUrl = "https://pub-012e0e3c1b2643639bffe9b7fd5624e5.r2.dev/AlexPhamBlog_logo.png"

  # Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      anonymizeIP = true

  # Cookie consent config
  [params.cookieconsent]
    enable = false

  # CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    data = ""

  # Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags in Markdown content
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  # privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/myDir/en"

  [languages.vi]
    languageName = "Tiếng Việt"
    weight = 2
    contentDir = "content/myDir/vi"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":git"]